apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: hk9ubimjb-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hk9ubimjb-go 
  name: hk9ubimjb-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: hk9ubimjb-go 
